export const PRODUCTS_SET_IS_FETCHING_PRODUCTS = 'PRODUCTS_SET_IS_FETCHING_PRODUCTS';
export const PRODUCTS_SET_PRODUCTS = 'SET_PRODUCTS';
export const PRODUCTS_ADD_PRODUCT = 'PRODUCTS_ADD_PRODUCT';
export const PRODUCTS_DELETE_PRODUCT = 'PRODUCTS_DELETE_PRODUCT';